soundcore
soundwire-bus
qcom_pil_info
mdt_loader
qmi_helpers
snd-q6dsp-common
rpmsg_char
qcom_glink_smem
qrtr
qrtr-smd
snd
qcom_pdr_msg
qcom_sysmon
rpmsg_ctrl
snd-timer
pdr_interface
qcom_pd_mapper
qcom_q6v5
qcom_common
snd-pcm
qcom_q6v5_pas
apr
snd-compress
fastrpc
snd-soc-core
lpassaudiocc_sc7280
pinctrl_lpass_lpi
pinctrl_sc7280_lpass_lpi
regmap_sdw
slimbus
soundwire_qcom
snd-soc-lpass-macro-common
snd-soc-lpass-wsa-macro
snd-soc-lpass-va-macro
snd-soc-wsa883x
snd-soc-hdmi-codec
audioreach_driver
