blacklist coresight_etm4x
blacklist coresight_funnel
blacklist coresight_replicator
blacklist coresight_tmc
blacklist coresight_cti
blacklist coresight_tpdm
blacklist coresight_stm

install coresight_etm4x      /bin/false
install coresight_funnel     /bin/false
install coresight_replicator /bin/false
install coresight_tmc        /bin/false
install coresight_cti        /bin/false
install coresight_tpdm       /bin/false
install coresight_stm        /bin/false
