softdep lontium_lt9611uxc  pre: msm
softdep aux_bridge         pre: msm pmic_glink_altmode lontium_lt9611uxc
softdep aux_hpd_bridge     pre: msm pmic_glink_altmode
softdep display_connector  pre: msm
