drm
drm_kms_helper
drm_client_lib
drm_dp_aux_bus
drm_display_helper
gpucc_sc7280
gpu_sched
drm_gpuvm
msm_kgsl
i2c_qcom_geni
gpi
dispcc_sc7280
phy_qcom_edp
phy_qcom_qmp_combo
aux_hpd_bridge
pmic_glink
pmic_glink_altmode
nb7vpq904m
display_connector
snd_soc_hdmi_codec
lontium_lt9611uxc
aux_bridge
msm
