# List of kernel modules required for camera functionality.
# Loaded early during boot via systemd-modules-load.service to reduce camera startup latency.

mc
videodev
mdt_loader
llcc_qcom
camcc_sa8775p
camera_qcs9100
ubwc_config
msm_kgsl
videobuf2_common
videobuf2_v4l2
v4l2_mem2mem
iris_vpu
msm

