# List of Qualcomm and generic display/GPU kernel modules.
# Loaded early via systemd-modules-load to accelerate display bring-up.

mdt_loader
drm_kms_helper
drm_core_init
socinfo
display_connector
gpucc_sa8775p
dispcc1_sa8775p
llcc_qcom
gpi
dispcc0_sa8775p
drm_dp_aux_bus
drm_display_helper
gpu_sched
ocmem
msm
typec
phy_qcom_edp
